### ISSUE TITLE
Internal date not updated when clickOnDate implemented

### ISSUE THREAD

**Issue by gertjanmaas** [boyarskiy/react-simple-datepicker#2]
I implemented the clickOnDate function, but I noticed the date showing on the component (and its internal state) is not updated when handling this.
Also giving the updated date back via props doesn't seem to make it update.

I see there is a return statement when calling clickOnDate at https://github.com/boyarskiy/react-simple-datepicker/blob/master/src/Datepicker.js#L85 . Should that be there?

**Comment by vernondegoede** [comment]
@gertjanmaas You're right. `setState` should be invoked before invoking the callback. I can submit a PR for this today.
