### ISSUE TITLE
Need help in using 'clickOnDate'

### ISSUE THREAD

**Issue by smilingpigs** [boyarskiy/react-simple-datepicker#5]
I am not sure how to use 'clickOnDate' as I want the value of newly selected date. Can you please tell me how do I use this to get the newly selected date? Thanks.

**Comment by boyarskiy** [comment]
Hi @smilingpigs 
You need to pass `clickOnDate` prop to the `Datepicker` component - https://github.com/boyarskiy/react-simple-datepicker/blob/master/example/app/index.js#L14

**Comment by smilingpigs** [comment]
Thanks @boyarskiy
